### ISSUE TITLE
Make Configuration serializable and add hashCode + equals

### ISSUE THREAD

**Issue by mlytvyn** [klaushauschild1984/jhac#17]
It would be nice to store Configuration in the Map, could you please add `hashCode` and `equals`

**Comment by jlolling** [comment]
I think we can let Lombok do the job

**Comment by klaushauschild1984** [comment]
Will cleanup the open PR

**Comment by klaushauschild1984** [comment]
@mlytvyn why do you need serialization for `Configuration`? Are you planning to write it actually into a file?

**Comment by mlytvyn** [comment]
yes, as one possible option, but that's absolutely optional. HashCode and Equals most important

**Comment by klaushauschild1984** [comment]
`equals()` and `hashCode()` are there
