### ISSUE TITLE
Ensure that FSQ result map has columns in lowercase

### ISSUE THREAD

**Issue by mlytvyn** [klaushauschild1984/jhac#21]
It would be great to have some guarantee that List of Map which we get from `QueryResult.asMap` will return Map with lowercased keys (headers).
We are using exact key mapping, which is defined dynamically, to get value from the map.
It would be great to ensure that API will return same values for the same key between versions.

**Comment by klaushauschild1984** [comment]
`QueryResult.asMap` has either lowercasing by default or an overloaded version with boolean parameter
